# App
spring.application.name=society-portal
server.port=${PORT:8080}
# PostgreSQL (Neon DB - still OK locally if internet works)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Hikari
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.maximum-pool-size=5

# JWT
app.jwt.secret=ReplaceWithAStrongSecretKeyThatIsLong
app.jwt.expirationMs=86400000

spring.mail.host=in-v3.mailjet.com
spring.mail.port=587
spring.mail.username=${MAILJET_API_KEY}
spring.mail.password=${MAILJET_SECRET_KEY}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# ✅ DEBUG (IMPORTANT)
